---
name: ReleaseBuild

on:
  workflow_run:
    workflows: [TestBuild]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Extract version from tag
        id: extract_version
        shell: bash
        run: echo "release_version=$(git tag | sort -n | tail -1)" >>$GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        id: configure-login-dockerhub
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and publish release
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            zasema/paradigma:${{ steps.extract_version.outputs.release_version }}
            ghcr.io/zasema/paradigma:${{ steps.extract_version.outputs.release_version }}
