---
name: TestRC

on:
  push:
    branches:
      - 'releases/paradigma-*'

env:
  PYTHON_VERSION: '3.8.12'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Run unit-tests
        run: pytest --cov