apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
  name: {{ .Values.simpleserver.name }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.simpleserver.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.simpleserver.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.simpleserver.name }}
    spec:
      containers:
      - name: {{ .Values.simpleserver.name }}
        image: {{ .Values.simpleserver.image }}
        imagePullPolicy: {{ .Values.simpleserver.imagePullPolicy }}
        livenessProbe:
          failureThreshold: {{ .Values.simpleserver.livenessProbe.failureThreshold }}
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: {{ .Values.simpleserver.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.simpleserver.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.simpleserver.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.simpleserver.livenessProbe.timeoutSeconds }}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: {{ .Values.simpleserver.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.simpleserver.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.simpleserver.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.simpleserver.readinessProbe.timeoutSeconds }}
        ports:
        - name: api
          containerPort: 8081
          protocol: TCP
        - name: metrics
          containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
