apiVersion: v1
kind: Service
metadata:
  labels:
   {{- include "helm.labels" . | nindent 4 }}
    app: {{ .Values.simpleserver.name }}
  name: {{ .Values.simpleserver.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.simpleserver.name }}
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: {{ .Values.simpleserver.name }}
