{
 "title": "Number of calls to endpoints",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of calls to server in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(server_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to main endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(main_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Memory usage vs Memory requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (pod)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"$pod\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Number of calls to healthcheck endpoint in the last hour",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "healthcheck_requests_total{namespace=\"$namespace\"} - min_over_time(healthcheck_requests_total{namespace=\"$namespace\"} [1h])"
    }
   ]
  }
 ]
}