apiVersion: v1
kind: Service
metadata:
  name: {{ include "paradigma.fullname" . }}
  labels:
    {{- include "paradigma.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  #vincular con la ip del helm de terraform de la fastapi
  loadBalancerIP: {{ .Values.controller.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.svc.port }}
      targetPort: {{ .Values.metrics.svc.port }}
      protocol: TCP
      name: {{ .Values.metrics.svc.name }}
    {{- end }}
  selector:
    {{- include "paradigma.selectorLabels" . | nindent 4 }}
