# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
# argocd-image-updater app
- name: argocd-image-updater
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.9.1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  additionalAnnotations:
    argocd.argoproj.io/sync-wave: "1"

# paradigma
- name: paradigma
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    helm:
      releaseName: my-app
      valueFiles:
        - values.yaml
    path: paradigma
    repoURL: 'git@github.com:zasema/paradigma-argocd.git'
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: paradigma-fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  additionalAnnotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-repo-creds-paradigma-creds
    argocd-image-updater.argoproj.io/main.update-strategy: semver
    argocd-image-updater.argoproj.io/main.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/main.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/main.force-update: 'true'
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: >-
      main=zasema/paradigma
    argocd-image-updater.argoproj.io/main.pull-secret: >-
      pullsecret:paradigma-fastapi/reg-cred-argocd-image-updater

- name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.9.0
    helm:
      releaseName: sealed-secrets
      parameters:
      - name: "secretName"
        value: "sealed-secrets-key"
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  additionalAnnotations:
    argocd.argoproj.io/sync-wave: "0"

#
# TODO: No termina de levantar todo el stack de kube-prometheus,
#       por tanto, se deja comentado de momento
#
## prometheus
#- name: prometheus
#  namespace: argocd
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
#  project: default
#  source:
#    chart: kube-prometheus-stack
#    repoURL: https://prometheus-community.github.io/helm-charts
#    targetRevision: 46.6.0
#    helm:
#      releaseName: my-metrics
#      valueFiles:
#        - values.yaml
#    path: kube-prometheus-stack
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: monitoring
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true
#  ignoreDifferences:
#  - group: apps
#    kind: Deployment
#    jsonPointers:
#    - /spec/replicas
#  additionalAnnotations:
#    argocd.argoproj.io/sync-wave: "3"

