apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  name: bd-data
  namespace: {{ .Values.namespace }}
data:
  MYSQL_DATABASE: cds
  MYSQL_HOST: {{ .Values.mysql.name }}
