apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }} 
  name: {{ .Values.apache.name }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.apache.name }}
            port: 
              number: 80
