apiVersion: batch/v1
kind: Job
metadata:
  labels:
      {{- include "helm.labels" . | nindent 4 }}
    job-name: init-db
  name: init-db
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: {{ .Values.initdb.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: {{ .Values.initdb.name }}
    spec:
      containers:
      - name: {{ .Values.initdb.name }}
        image: {{ .Values.initdb.image }}
        envFrom:
        - configMapRef:
            name: bd-data
        - secretRef:
            name: bd-credentials
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
