apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  name: bd-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.connection.data.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: {{ .Values.connection.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.connection.data.MYSQL_USER }}
