apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }} 
    app: {{ .Values.mysql.name }}
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.mysql.name }}
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: {{ .Values.mysql.name }}
