apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app: {{ .Values.mysql.name }}
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  serviceName: "mysql"
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.image }}
        envFrom:
        - configMapRef:
            name: bd-data
        - secretRef:
            name: bd-credentials
        ports:
        - name: {{ .Values.mysql.name }}
          containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      dnsPolicy: ClusterFirst
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
      
