jenkins_master:
  image: jenkins/jenkins:2.361.1-lts-jdk11
  container_name: jenkins_master
  user: root
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - ./jenkins:/var/jenkins_home
  ports:
    - 127.0.0.1:2345:2345
    - 8080:8080
    - 50000:50000
