apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: init-db
  name: init-db
  namespace: kmmb82
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: init-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: init-db
    spec:
      containers:
      - name: init-db
        image: marianomb82/mmb82-init_db:v1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
        - configMapRef:
            name: bd-data
        - secretRef:
            name: bd-credentials
      restartPolicy: Never
